 
INIT_GAME:
 
  LD    BC,GA_PORT+(RMR_CTRL+ROM_OFF+MODE_0) : OUT (C),C
  
  GA_mSETBGCOLOR     INK_BLACK
  GA_mSETBORDERCOLOR INK_BLACK
  
  GA_mSETPENCOLOR PEN_1, INK_PINK  
  GA_mSETPENCOLOR PEN_11,INK_PASTEL_YELLOW
  
  RET
  