 
InitialiseCPC:
 
  LD    BC,GA_PORT+(RMR_CTRL+ROM_OFF+MODE_0) : OUT (C),C
  
  mSETBGCOLOR INK_BLACK  
  mSETBORDERCOLOR INK_BLACK  
  mSETPENCOLOR PEN_1, INK_PINK  
  mSETPENCOLOR PEN_8, INK_PASTEL_GREEN
  
  RET
  